#  Assignment 5

This assignment covers material on matrices, norms, condition numbers and eigensystems.

The breakdown of the marks is as follows:

Question 0 - [1 mark]  
Question 1 - [7 marks]  
Questino 2 - [6 marks]  
Question 3 - [7 marks]  
Question 4 - [9 marks]  

# Question 0

You should have saved this notebook to your ACM20030-Assignments folder. Now:
- commit the notebook to your local repository
- push the changes to the GitHub

In [25]:
import numpy as np
from numpy import linalg as la
np.set_printoptions(linewidth=200)  # This stops line wrapping of larger matrices

# Question 1 - practice manipulating arrays

This questions asks you write a few functions for manipulating arrays of data

## Q1 a

Write a function that checks if a given $n\times n$ matrix is symmetric. Use only loops and `.shape` function from numpy (do not use any other special numpy functions).

In [26]:
def SymCheck(A):
    imax=A.shape[0]
    jmax=A.shape[1]
    i=0
    j=0
    while i<imax:
        j=i
        while j<jmax:
            if A[i][j]==A[j][i]:
                j+=1
            else:
                print("This matrix is not symmetric.")
                return
        i+=1
    
    print("This matrix is symmetric.")
    return
                

Test your function on the two matrices below

In [27]:
A = np.random.rand(5,5)
SymMatrix = (A + A.T)/2
SymCheck(SymMatrix)

This matrix is symmetric.


## Q1 b

Write a function to transpose a general $n\times n$ matrix. Do this by writing loops and not using any special functions like `np.transpose()`, `A.T`, or any functions from any other library (`np.zeroes`, `np.ones`, `np.shape`, etc are all ok to use).

In [28]:
B = np.random.rand(5,5)

def MatTranspose(B):
    imax=B.shape[0]
    jmax=B.shape[1]
    i=0
    j=0
    B_T=np.zeros([B.shape[0],B.shape[1]])
    while i<imax:
        
        while j<jmax:
            B_T[j][i]=B[i][j]
            j+=1
        i+=1
        j=0
    return B_T

Check your code by transposing a matrix by checking that $A^T \neq A$ and $(A^T)^T - A = 0$

In [29]:
B = np.random.rand(6,6);
B_T=MatTranspose(B)
if (B==B_T).all():
    print("Equal")
else:
    print("Not Equal")
    
B_TT=MatTranspose(B_T)
print("B_TT-B=\n",B_TT-B)

Not Equal
B_TT-B=
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


## Q1c

Write a function that finds the maximum entry in a matrix (where the matrix does not need to be square). Do this by writing loops and not using any special functions like `np.max` or any functions from any other library.

In [30]:
def MaxFinder(C):
    imax=C.shape[0]
    jmax=C.shape[1]
    i=0
    j=0
    maxent=0
    
    while i<imax:
        
        while j<jmax:
            
            if C[i][j]>maxent:
                maxent=C[i][j]
                
            j+=1
            
        i+=1
        j=0
            
    return maxent

Check your result by comparing to `np.max(A)` for the below random matrix

In [31]:
C = np.random.rand(4,5)
maxent=MaxFinder(C)
if np.max(C)==maxent:
    print("These results agree that the max of C is",maxent)
else:
    print("These results do not agree.")


These results agree that the max of C is 0.9702267873412641


Commit your notebook to git and push it to GitHub.

# Question 2:  matrix norms

In the lectures we focused on the $L^2$-norm. We also briefly mentioned the $L^1$ and $L^\infty$ norm. Let's look at calculating those as well for a general $m\times n$ matrix.

# Q2a

The $L^1$ norm is given by

$$ \lVert A \rVert_1 = \max_j \sum^m_{i=1} |a_{ij}| $$

i.e., it is the max of the sums of the absolute values of each column. Write a function that computes the $L^1$-norm using only loops. The function should use no special numpy functions except `np.abs()` (`np.shape`, `np.inf`, etc are ok to use).

In [32]:
def L1Norm(D):
    imax=D.shape[0]
    jmax=D.shape[1]
    i=0
    j=0
    maxsum1=0
    temp=0
    
    while j<jmax:
        while i<imax:
            temp+=D[i][j]
            i+=1
        if temp>maxsum1:
            maxsum1=temp
        i=0
        j+=1
        temp=0
    return maxsum1

Check your result against NumPy's `la.norm(A,1)` function for the following random matrix

In [33]:
D = np.random.rand(3,4)
maxsum1=L1Norm(D)
if maxsum1==la.norm(D,1):
    print("These results agree that the L1 norm of D is",maxsum1)
else:
    print("These results do not agree")

These results agree that the L1 norm of D is 1.5019828548348138


## Q2b

The $L^\infty$ norm is given by 

$$\lVert A \rVert_\infty = \max_i \sum_{j=1}^n |a_{ij}|$$

i.e., it is the max of the sums of the absolute values of each row. Write a function that computes the $L^\infty$-norm using only loops and no special numpy functions.

In [34]:
def LINorm(D):
    imax=D.shape[0]
    jmax=D.shape[1]
    i=0
    j=0
    maxsumI=0
    temp=0
    
    while i<imax:
        while j<jmax:
            temp+=D[i][j]
            j+=1
        if temp>maxsumI:
            maxsumI=temp
        j=0
        i+=1
        temp=0
    return maxsumI

Check your result against NumPy's `la.norm(A,np.inf)` function for the following random matrix

In [35]:
E = np.random.rand(3,4)
maxsumI=LINorm(E)
if maxsumI==la.norm(E,np.inf):
    print("These results agree that the infinite norm of E is", maxsumI)
else:
    print("These results do not agree")


These results agree that the infinite norm of E is 2.1567313570205675


Commit your notebook to git and push it to GitHub.

# Question 3: ill-conditions systems of equations

In this question you can use any of NumPy's functions.

## Q3a

Which of the following three matrices, $A1, A2, A3$, are ill-conditioned. State the reason for your conclusion.

In [36]:
A1 = np.array([[ 2.852416473483e-01,  3.803483118694e-01,  2.697704226632e-01,  6.810611849029e-01],
       [ 6.622827828376e-01,  6.447943415836e-01,  4.387842058829e-01,  1.530575702376e+00],
       [ 3.672130860703e-01,  8.309522079704e-01,  9.975487474007e-01,  5.678296337101e-01],
       [ 4.036490000599e-01,  6.865978225967e-06,  8.788095913773e-01, -7.150472427928e-02]])

A2 = np.array([[0.988746460106, 0.351486109477, 0.024911477532, 0.384039749683],
       [0.282104657306, 0.239884151775, 0.36170151991 , 0.903082266861],
       [0.59333290915 , 0.637178863968, 0.241229214635, 0.685595037901],
       [0.013591747828, 0.917926970364, 0.458689093885, 0.157821121254]])

A3 = np.array([[0.131923621844, 0.245316154195, 0.732362341613, 0.957047891764],
       [0.91290446184 , 0.512312007959, 0.391938831444, 0.092509684772],
       [0.648708523652, 0.608576675797, 0.576773587276, 0.065385122929],
       [0.502955480393, 0.084082960221, 0.659487390444, 0.662958739412]])

In [37]:
#Condition number for A1
A1CN=(la.norm(A1,2))*(la.norm(la.inv(A1),2))

#Condition number for A2
A2CN=(la.norm(A2,2))*(la.norm(la.inv(A2),2))

#Condition number for A3
A3CN=(la.norm(A3,2))*(la.norm(la.inv(A3),2))

print("A1's condition number is",A1CN,"\nA2's condition number is",A2CN,"\nA3's condition number is",A3CN)

A1's condition number is 13334921820.764688 
A2's condition number is 21.552466488381857 
A3's condition number is 15.122449699410627


# Q3b

With $b = [1,2,3,4]$ and $\delta b = [0.1,0,0,0]$ for $A1$ and $A2$ calculate the percentage change in $x$ due to a small change in $b$, i.e., calculate 

$$100\times\frac{\lVert \delta x_i\rVert_2}{\lVert x_i \rVert_2}\quad\text{and}\quad 100\times\frac{\lVert \delta b\rVert_2}{\lVert b \rVert_2}$$

where $(x_i+\delta x_i)  = A_i^{-1}(b+\delta b)$ and $i\in\{1,2\}$.

In [38]:
b=np.array([[1],[2],[3],[4]])
db=np.array([[0.1],[0],[0],[0]])

cb=100*(la.norm(db,2))/(la.norm(b,2))

#Finding the percentages for A1
A1inv=la.inv(A1)
dx1=A1inv*(b+db)-A1
cx1=100*(la.norm(dx1,2))/(la.norm(A1,2))

#Finding the Percentages for A2
A2inv=la.inv(A2)
dx2=A2inv*(b+db)-A2
cx2=100*(la.norm(dx2,2))/(la.norm(A2,2))

print("The percentages for A1 are approximately {:.0%} for b, and {:.0%} for x".format(cb,cx1))
print("The percentages for A2 are approximately {:.0%} for b, and {:.0%} for x".format(cb,cx2))

The percentages for A1 are approximately 183% for b, and 49518246157651% for x
The percentages for A2 are approximately 183% for b, and 175273% for x


Which system of equations is more sensitive to small changes in $b$? How could you have guessed this from the answer to the Q3a?

In [39]:
#The system A1 is far more sensitive to small changes in b, this could have been seen in Q3a from the fact that it's condition
#number is so large.


Commit your notebook to git and push it to GitHub.

# Question 4: eigensystems

In this question we look at finding eigenvalues and eigenvectors

## Q4a

You may use any of NumPy's functions for this sub-question.

Find the eigenvalues and eigenvectors for the below matrix. Print out the eigenvalues sorted by descending value and explicitly show that eigenvalues/eigenvector pairs satisfy $Ax = \lambda x$.

In [40]:
F = np.array([[1,4,5],[4,5,4],[6,7,9]])
print(F)

[[1 4 5]
 [4 5 4]
 [6 7 9]]


In [41]:
eigval,eigvec=la.eig(F)
idx = np.argsort(eigval)[::-1]
eigval = eigval[idx]
eigvec = eigvec[:,idx]
print("The three eigenvalues for the matrix F are",eigval,"\n")

for i in range(0,3):
    Fx=np.dot(F,eigvec[:,i])
    ex=np.dot(eigval[i],eigvec[:,i])
    
    if (Fx==ex).all:
        print("The results agree for F*x and e*x, we can see the following.","\nF*x=",Fx,"and e*x=",ex,"\n")

The three eigenvalues for the matrix F are [15.78569318  1.26595327 -2.05164645] 

The results agree for F*x and e*x, we can see the following. 
F*x= [ -6.1962015   -7.01266016 -12.71289871] and e*x= [ -6.1962015   -7.01266016 -12.71289871] 

The results agree for F*x and e*x, we can see the following. 
F*x= [ 0.12430099 -0.98053324  0.79103825] and e*x= [ 0.12430099 -0.98053324  0.79103825] 

The results agree for F*x and e*x, we can see the following. 
F*x= [ 1.83806756 -0.74382849 -0.52676368] and e*x= [ 1.83806756 -0.74382849 -0.52676368] 



# Q4b

Without using NumPy's `la.eig()` (or similar functions), find the 4 eigenvalues and eigenvectors of the following matrix. Hint: Use the power method for the max eigenvalue (given below in `MaxEigenvalue`), the power method applied to the inverse for the smallest eigenvalue, and apply Hotelling's deflation twice to find the second and third eigenvalues/eigenvectors.

In [20]:
A = np.array([[2.65287619, 1.58615494, 1.47170961, 1.40586081],
       [1.58615494, 1.17577323, 0.72084593, 0.79382861],
       [1.47170961, 0.72084593, 1.18111969, 0.6654689 ],
       [1.40586081, 0.79382861, 0.6654689 , 0.84502394]])

Check your answers against Numpy's results from `la.eig(A)`

Commit your notebook to git and push it to GitHub. Upload your completed assignment to BrightSpace.